"""Dữ liệu đề thi luyện nghe chuẩn hoá cho HSK 1 đến HSK 6."""

LISTENING_EXAMS_HSK1_6 = [
    # HSK 1
    {
        "title": "HSK 1 · Nghe hiểu: Chào hỏi & Làm quen",
        "hsk": 1,
        "duration_minutes": 10,
        "questions": [
            {
                "id": "hsk1_l1_q1",
                "section": "listening",
                "prompt": "Người nói tên là gì?",
                "options": ["Lý Hoa (李华)", "Tiểu Minh (小明)", "Vương Phương (王芳)"],
                "answer": "Lý Hoa (李华)",
                "transcript": "你好！我叫李华，很高兴认识你。(Nǐ hǎo! Wǒ jiào Lǐ Huá, hěn gāoxìng rènshí nǐ.)",
                "explanation": "我叫李华 nghĩa là Tôi tên Lý Hoa. 很高兴认识你 là rất vui được làm quen với bạn.",
                "audio_url": "https://translate.google.com/translate_tts?ie=UTF-8&tl=zh-CN&client=tw-ob&q=%E4%BD%A0%E5%A5%BD%EF%BC%81%E6%88%91%E5%8F%AB%E6%9D%8E%E5%8D%8E%EF%BC%8C%E5%BE%88%E9%AB%98%E5%85%B4%E8%AE%A4%E8%AF%86%E4%BD%A0%E3%80%82",
                "word_id": None,
            },
            {
                "id": "hsk1_l1_q2",
                "section": "listening",
                "prompt": "Hôm nay là thứ mấy?",
                "options": ["Thứ sáu (星期五)", "Thứ bảy (星期六)", "Chủ nhật (星期天)"],
                "answer": "Thứ sáu (星期五)",
                "transcript": "今天星期几？今天星期五。(Jīntiān xīngqī jǐ? Jīntiān xīngqīwǔ.)",
                "explanation": "星期五 nghĩa là thứ sáu trong tuần.",
                "audio_url": "https://translate.google.com/translate_tts?ie=UTF-8&tl=zh-CN&client=tw-ob&q=%E4%BB%8A%E5%A4%A9%E6%98%9F%E6%9C%9F%E5%87%A0%EF%BC%9F%E4%BB%8A%E5%A4%A9%E6%98%9F%E6%9C%9F%E4%BA%94%E3%80%82",
                "word_id": None,
            },
            {
                "id": "hsk1_l1_q3",
                "section": "listening",
                "prompt": "Người nói muốn uống gì?",
                "options": ["Trà (茶)", "Cà phê (咖啡)", "Nước lọc (水)"],
                "answer": "Trà (茶)",
                "transcript": "你想喝什么？我想喝一杯茶。(Nǐ xiǎng hē shénme? Wǒ xiǎng hē yì bēi chá.)",
                "explanation": "想喝一杯茶 nghĩa là muốn uống một tách trà.",
                "audio_url": "https://translate.google.com/translate_tts?ie=UTF-8&tl=zh-CN&client=tw-ob&q=%E4%BD%A0%E6%83%B3%E5%96%9D%E4%BB%80%E4%B9%88%EF%BC%9F%E6%88%91%E6%83%B3%E5%96%9D%E4%B8%80%E6%9D%AF%E8%8C%B6%E3%80%82",
                "word_id": None,
            },
        ],
    },
    # HSK 2
    {
        "title": "HSK 2 · Nghe hiểu: Đời sống & Di chuyển",
        "hsk": 2,
        "duration_minutes": 12,
        "questions": [
            {
                "id": "hsk2_l1_q1",
                "section": "listening",
                "prompt": "Thời tiết bên ngoài như thế nào?",
                "options": ["Trời đang mưa (下雨)", "Trời nhiều mây (阴天)", "Trời có tuyết (下雪)"],
                "answer": "Trời đang mưa (下雨)",
                "transcript": "外面下雨了，你出门别忘了带雨伞。(Wàimiàn xiàyǔ le, nǐ chūmén bié wàng le dài yǔsǎn.)",
                "explanation": "下雨 nghĩa là trời mưa, 雨伞 là cây ô/dù che mưa.",
                "audio_url": "https://translate.google.com/translate_tts?ie=UTF-8&tl=zh-CN&client=tw-ob&q=%E5%A4%96%E9%9D%A2%E4%B8%8B%E9%9B%A8%E4%BA%86%EF%BC%8C%E4%BD%A0%E5%87%BA%E9%97%A8%E5%88%AB%E5%BF%98%E4%BA%86%E5%B8%A6%E9%9B%A8%E4%BC%9E%E3%80%82",
                "word_id": None,
            },
            {
                "id": "hsk2_l1_q2",
                "section": "listening",
                "prompt": "Đi xe buýt đến ga xe lửa mất bao lâu?",
                "options": ["Nửa tiếng (半个小时)", "Một tiếng (一个小时)", "Mười lăm phút (十五分钟)"],
                "answer": "Nửa tiếng (半个小时)",
                "transcript": "从这里坐公共汽车去火车站需要半个小时。(Cóng zhèlǐ zuò gōnggòng qìchē qù huǒchēzhàn xūyào bàn gè xiǎoshí.)",
                "explanation": "公共汽车 là xe buýt, 半个小时 là nửa giờ (30 phút).",
                "audio_url": "https://translate.google.com/translate_tts?ie=UTF-8&tl=zh-CN&client=tw-ob&q=%E4%BB%8E%E8%BF%99%E9%87%8C%E5%9D%90%E5%85%AC%E5%85%B1%E6%B1%BD%E8%BD%A6%E5%8E%BB%E7%81%AB%E8%BD%A6%E7%AB%99%E9%9C%80%E8%A6%81%E5%8D%8A%E4%B8%8A%E5%B0%8F%E6%97%B6%E3%80%82",
                "word_id": None,
            },
            {
                "id": "hsk2_l1_q3",
                "section": "listening",
                "prompt": "Người nói đang tìm đồ vật gì?",
                "options": ["Điện thoại di động (手机)", "Ví tiền (钱包)", "Chìa khóa (钥匙)"],
                "answer": "Điện thoại di động (手机)",
                "transcript": "你看见我的手机了吗？我记得放在桌子上了。(Nǐ kànjiàn wǒ de shǒujī le ma? Wǒ jìdé fàng zài zhuōzi shàng le.)",
                "explanation": "手机 là điện thoại di động, 桌子上 là trên bàn.",
                "audio_url": "https://translate.google.com/translate_tts?ie=UTF-8&tl=zh-CN&client=tw-ob&q=%E4%BD%A0%E7%9C%8B%E8%A7%81%E6%88%91%E7%9A%84%E6%89%8B%E6%9C%BA%E4%BA%86%E5%90%97%EF%BC%9F%E6%88%91%E8%AE%B0%E5%BE%97%E6%94%BE%E5%9C%A8%E6%A1%8C%E5%AD%90%E4%B8%8A%E4%BA%86%E3%80%82",
                "word_id": None,
            },
        ],
    },
    # HSK 3
    {
        "title": "HSK 3 · Nghe hiểu: Kế hoạch & Du lịch",
        "hsk": 3,
        "duration_minutes": 15,
        "questions": [
            {
                "id": "hsk3_l1_q1",
                "section": "listening",
                "prompt": "Họ dự định đi đâu vào mùa nào?",
                "options": ["Bắc Kinh vào mùa thu", "Thượng Hải vào mùa xuân", "Tây An vào mùa đông"],
                "answer": "Bắc Kinh vào mùa thu",
                "transcript": "我们打算下个月去北京旅游，听说秋天的北京最美丽。(Wǒmen dǎsuàn xià gè yuè qù Běijīng lǚyóu, tīngshuō qiūtiān de Běijīng zuì měilì.)",
                "explanation": "打算 là dự định, 北京 là Bắc Kinh, 秋天 là mùa thu.",
                "audio_url": "https://translate.google.com/translate_tts?ie=UTF-8&tl=zh-CN&client=tw-ob&q=%E6%88%91%E4%BB%AC%E6%89%93%E7%AE%97%E4%B8%8B%E4%B8%AA%E6%9C%88%E5%8E%BB%E5%8C%97%E4%BA%AC%E6%97%85%E6%B8%B8%EF%BC%8C%E5%90%AC%E8%AF%B4%E7%A7%8B%E5%A4%A9%E7%9A%84%E5%8C%97%E4%BA%AC%E6%9C%80%E7%BE%8E%E4%B8%BD%E3%80%82",
                "word_id": None,
            },
            {
                "id": "hsk3_l1_q2",
                "section": "listening",
                "prompt": "Tình trạng tài liệu hiện tại như thế nào?",
                "options": ["Đã kiểm tra kỹ, có thể in", "Chưa đọc xong tài liệu", "Có nhiều lỗi cần viết lại"],
                "answer": "Đã kiểm tra kỹ, có thể in",
                "transcript": "这份材料我已经仔细检查过了，没有任何问题，可以直接打印。(Zhè fèn cáiliào wǒ yǐjīng zǐxì jiǎnchá guò le, méiyǒu rènhé wèntí, kěyǐ zhíjiē dǎyìn.)",
                "explanation": "仔细检查 nghĩa là kiểm tra cẩn thận, 打印 là in ấn.",
                "audio_url": "https://translate.google.com/translate_tts?ie=UTF-8&tl=zh-CN&client=tw-ob&q=%E8%BF%99%E4%BB%BD%E6%9D%90%E6%96%99%E6%88%91%E5%B7%B2%E7%BB%8F%E4%BB%94%E7%BB%86%E6%A3%80%E6%9F%A5%E8%BF%87%E4%BA%86%EF%BC%8C%E6%B2%A1%E6%9C%89%E4%BB%BB%E4%BD%95%E9%97%AE%E9%A2%98%EF%BC%8C%E5%8F%AF%E4%BB%A5%E7%9B%B4%E6%8E%A5%E6%89%93%E5%8D%B0%E3%80%82",
                "word_id": None,
            },
            {
                "id": "hsk3_l1_q3",
                "section": "listening",
                "prompt": "Bác sĩ khuyên bệnh nhân điều gì?",
                "options": ["Uống nhiều nước ấm và nghỉ ngơi", "Đi tập thể thao ngay", "Tiếp tục làm việc tăng ca"],
                "answer": "Uống nhiều nước ấm và nghỉ ngơi",
                "transcript": "你最近感冒了，要记得按时吃药，多喝温水，好好休息。(Nǐ zuìjìn gǎnmào le, yào jìdé ànshí chīyào, duō hē wēnshuǐ, hǎohāo xiūxi.)",
                "explanation": "按时吃药 (uống thuốc đúng giờ), 多喝温水 (uống nhiều nước ấm), 好好休息 (nghỉ ngơi dưỡng sức).",
                "audio_url": "https://translate.google.com/translate_tts?ie=UTF-8&tl=zh-CN&client=tw-ob&q=%E4%BD%A0%E6%83%B3%E5%96%9D%E4%BB%80%E4%B9%88%EF%BC%9F%E6%88%91%E6%83%B3%E5%96%9D%E4%B8%80%E6%9D%AF%E8%8C%B6%E3%80%82",
                "word_id": None,
            },
        ],
    },
    # HSK 4
    {
        "title": "HSK 4 · Nghe hiểu: Công việc & Giao tiếp",
        "hsk": 4,
        "duration_minutes": 15,
        "questions": [
            {
                "id": "hsk4_l1_q1",
                "section": "listening",
                "prompt": "Buổi phỏng vấn diễn ra lúc mấy giờ và ở đâu?",
                "options": [
                    "9:30 sáng mai tại phòng họp số 3",
                    "9:00 sáng mai tại phòng họp số 1",
                    "2:00 chiều mai tại phòng nhân sự",
                ],
                "answer": "9:30 sáng mai tại phòng họp số 3",
                "transcript": "王经理，明天的面试安排在上午九点半的三号会议室，应聘者的简历我都准备好了。(Wáng jīnglǐ, míngtiān de miànshì ānpái zài shàngwǔ jiǔ diǎn bàn de sān hào huìyìshì, yìngpìnzhě de jiǎnlì wǒ dōu zhǔnbèi hǎo le.)",
                "explanation": "上午九点半 là 9h30 sáng, 三号会议室 là phòng họp số 3, 面试 là phỏng vấn.",
                "audio_url": "https://translate.google.com/translate_tts?ie=UTF-8&tl=zh-CN&client=tw-ob&q=%E7%8E%8B%E7%BB%8F%E7%90%86%EF%BC%8C%E6%98%8E%E5%A4%A9%E7%9A%84%E9%9D%A2%E8%AF%95%E5%AE%89%E6%8E%92%E5%9C%A8%E4%B8%8A%E5%8D%88%E4%B9%9D%E7%82%B9%E5%8D%8A%E7%9A%84%E4%B8%89%E5%8F%B7%E4%BC%9A%E8%AE%AE%E5%AE%A4%E3%80%82",
                "word_id": None,
            },
            {
                "id": "hsk4_l1_q2",
                "section": "listening",
                "prompt": "Theo người nói, đọc sách đem lại lợi ích gì?",
                "options": [
                    "Làm giàu tri thức và giảm căng thẳng công việc",
                    "Tăng thu nhập ngay trong tháng",
                    "Giảm thời gian giao tiếp hàng ngày",
                ],
                "answer": "Làm giàu tri thức và giảm căng thẳng công việc",
                "transcript": "养成良好的阅读习惯不仅能丰富知识，还能缓解日常工作的压力。(Yǎngchéng liánghǎo de yuèdú xíguàn bùjǐn néng fēngfù zhīshi, hái néng huǎnjiě rìcháng gōngzuò de yālì.)",
                "explanation": "丰富知识 nghĩa là bồi đắp/làm giàu kiến thức; 缓解压力 là giảm bớt áp lực.",
                "audio_url": "https://translate.google.com/translate_tts?ie=UTF-8&tl=zh-CN&client=tw-ob&q=%E5%85%BB%E6%88%90%E8%89%AF%E5%A5%BD%E7%9A%84%E9%98%85%E8%AF%BB%E4%B9%A0%E6%83%AF%E4%B8%8D%E4%BB%85%E8%83%BD%E4%B8%B0%E5%AF%8C%E7%9F%A5%E8%AF%86%EF%BC%8C%E8%BF%98%E8%83%BD%E7%BC%93%E8%A7%A3%E6%97%A5%E5%B8%B8%E5%B7%A5%E4%BD%9C%E7%8E%AF%E5%A2%83%E4%B8%AD%E7%9A%84%E5%8E%8B%E5%8A%9B%E3%80%82",
                "word_id": None,
            },
            {
                "id": "hsk4_l1_q3",
                "section": "listening",
                "prompt": "Tại sao người nói muốn đổi vé máy bay?",
                "options": [
                    "Vì có cuộc họp khẩn cấp vào sáng thứ hai",
                    "Vì thời tiết xấu chuyến bay bị hủy",
                    "Vì muốn ở lại du lịch thêm hai ngày",
                ],
                "answer": "Vì có cuộc họp khẩn cấp vào sáng thứ hai",
                "transcript": "不好意思，因为周一早上公司临时安排了一个重要会议，我想把周日晚上的航班改签到周日中午。(Bù hǎoyìsi, yīnwèi zhōuyī zǎoshang gōngsī línshí ānpái le yí gè zhòngyào huìyì, wǒ xiǎng bǎ zhōurì wǎnshang de hángbān gǎiqiān dào zhōurì zhōngwǔ.)",
                "explanation": "临时安排 (sắp xếp đột xuất/khẩn cấp), 重要会议 (cuộc họp quan trọng), 改签航班 (đổi giờ bay).",
                "audio_url": "https://translate.google.com/translate_tts?ie=UTF-8&tl=zh-CN&client=tw-ob&q=%E5%9B%A0%E4%B8%BA%E5%91%A8%E4%B8%80%E6%97%A9%E4%B8%8A%E5%85%AC%E5%8F%B8%E4%B8%B4%E6%97%B6%E5%AE%89%E6%8E%92%E4%BA%86%E4%B8%80%E4%B8%AA%E9%87%8D%E8%A6%81%E4%BC%9A%E8%AE%AE%EF%BC%8C%E6%88%91%E6%83%B3%E6%8A%8A%E8%88%AA%E7%8F%AD%E6%94%B9%E7%AD%BE%E3%80%82",
                "word_id": None,
            },
        ],
    },
    # HSK 5
    {
        "title": "HSK 5 · Nghe hiểu: Kinh tế & Xã hội hiện đại",
        "hsk": 5,
        "duration_minutes": 18,
        "questions": [
            {
                "id": "hsk5_l1_q1",
                "section": "listening",
                "prompt": "Sự phổ biến của thanh toán di động dẫn tới thay đổi gì?",
                "options": [
                    "Không cần mang tiền mặt vẫn chi tiêu tiện lợi",
                    "Người dân hạn chế mua sắm ngoài tiệm",
                    "Các cửa hàng truyền thống đóng cửa",
                ],
                "answer": "Không cần mang tiền mặt vẫn chi tiêu tiện lợi",
                "transcript": "随着移动支付的普及，人们的消费方式发生了深刻变革。如今出门即使不带现金，也能轻松满足餐饮、交通和购物的所有需求。(Suízhe yídòng zhīfù de pǔjí, rénmen de xiāofèi fāngshì fāshēng le shēnkè biàngé. Rújīn chūmén jíshǐ bù dài xiànjīn, yě néng qīngsōng mǎnzú cānyǐn, jiāotōng hé gòuwù de suǒyǒu xūqiú.)",
                "explanation": "移动支付 (thanh toán di động), 不带现金 (không đem tiền mặt), 满足所有需求 (đáp ứng mọi nhu cầu).",
                "audio_url": "https://translate.google.com/translate_tts?ie=UTF-8&tl=zh-CN&client=tw-ob&q=%E9%9A%8F%E7%9D%80%E7%A7%BB%E5%8A%A8%E6%94%AF%E4%BB%98%E7%9A%84%E6%99%AE%E5%8F%8A%EF%BC%8C%E4%BA%BA%E4%BB%AC%E5%87%BA%E9%97%A8%E5%8D%B3%E4%BD%BF%E4%B8%8D%E5%B8%A6%E7%8E%B0%E9%87%91%EF%BC%8C%E4%B9%9F%E8%83%BD%E8%BD%BB%E6%9D%BE%E6%BB%A1%E8%B6%B3%E6%89%80%E6%9C%89%E9%9C%80%E6%B1%82%E3%80%82",
                "word_id": None,
            },
            {
                "id": "hsk5_l1_q2",
                "section": "listening",
                "prompt": "Doanh nghiệp cần làm gì để đứng vững trước cạnh tranh?",
                "options": [
                    "Đổi mới công nghệ và nâng cao chất lượng dịch vụ",
                    "Hạ giá thành sản phẩm liên tục",
                    "Cắt giảm tối đa nhân sự kỹ thuật",
                ],
                "answer": "Đổi mới công nghệ và nâng cao chất lượng dịch vụ",
                "transcript": "面对激烈的市场竞争，企业只有不断推动技术创新、提升服务品质，才能在行业中立于不败之地。(Miànduì jīliè de shìchǎng jìngzhēng, qǐyè zhǐyǒu bùduàn tuīdòng jìshù chuàngxīn, tíshēng fúwù pǐnzhì, cáinéng zài hángyè zhōng lì yú bù bài zhī dì.)",
                "explanation": "技术创新 (sáng tạo/đổi mới kỹ thuật công nghệ), 提升服务品质 (nâng cao chất lượng dịch vụ).",
                "audio_url": "https://translate.google.com/translate_tts?ie=UTF-8&tl=zh-CN&client=tw-ob&q=%E9%9D%A2%E5%AF%B9%E6%BF%80%E7%83%88%E7%9A%84%E5%B8%82%E5%9C%BA%E7%AB%9E%E4%BA%89%EF%BC%8C%E4%BC%81%E4%B8%9A%E5%8F%AA%E6%9C%89%E4%B8%8D%E6%96%AD%E6%8E%A8%E5%8A%A8%E6%8A%80%E6%9C%AF%E5%88%9B%E6%96%B0%E3%80%81%E6%8F%90%E5%8D%87%E6%9C%8D%E5%8A%A1%E5%93%81%E8%B4%A8%E3%80%82",
                "word_id": None,
            },
            {
                "id": "hsk5_l1_q3",
                "section": "listening",
                "prompt": "Theo đoạn ghi âm, bí quyết để duy trì cân bằng công việc và cuộc sống là gì?",
                "options": [
                    "Quản lý thời gian khoa học và biết cách nói lời từ chối hợp lý",
                    "Làm thêm giờ vào cuối tuần để giải quyết việc tồn đọng",
                    "Bỏ qua mọi sở thích cá nhân khi đang bận rộn",
                ],
                "answer": "Quản lý thời gian khoa học và biết cách nói lời từ chối hợp lý",
                "transcript": "在快节奏的工作环境中，要想保持工作与生活的平衡，关键在于科学合理地规划时间，并学会适当地拒绝不合理的要求。(Zài kuàijìzòu de gōngzuò huánjìng zhōng, yào xiǎng bǎochí gōngzuò yǔ shēnghuó de pínghéng, guānjiàn zàiyú kēxué hélǐ de guīhuà shíjiān, bìng xuéhuì shìdàng de jùjué bù hélǐ de yāoqiú.)",
                "explanation": "科学合理规划时间 (quản lý thời gian khoa học), 拒绝不合理的要求 (từ chối yêu cầu không hợp lý).",
                "audio_url": "https://translate.google.com/translate_tts?ie=UTF-8&tl=zh-CN&client=tw-ob&q=%E5%9C%A8%E5%BF%AB%E8%8A%82%E5%A5%8F%E7%9A%84%E5%B7%A5%E4%BD%9C%E7%8E%AF%E5%A2%83%E4%B8%AD%EF%BC%8C%E8%A6%81%E6%83%B3%E4%BF%9D%E6%8C%81%E5%B7%A5%E4%BD%9C%E4%B8%8E%E7%94%9F%E6%B4%BB%E7%9A%84%E5%B9%B3%E8%A1%A1%EF%BC%8C%E5%85%B3%E9%94%AE%E5%9C%A8%E4%BA%8E%E7%A7%91%E5%AD%A6%E5%90%88%E7%90%86%E5%9C%B0%E8%A7%84%E5%88%92%E6%97%B6%E9%97%B4%E3%80%82",
                "word_id": None,
            },
        ],
    },
    # HSK 6
    {
        "title": "HSK 6 · Nghe hiểu: Văn hóa & Triết lý nghệ thuật",
        "hsk": 6,
        "duration_minutes": 20,
        "questions": [
            {
                "id": "hsk6_l1_q1",
                "section": "listening",
                "prompt": "Đặc trưng của nghệ thuật 'lưu bạch' trong tranh thủy mặc là gì?",
                "options": [
                    "Tạo khoảng trống gợi sức tưởng tượng phong phú và chiều sâu ý cảnh",
                    "Tiết kiệm mực vẽ và hoàn thành tranh nhanh hơn",
                    "Dành chỗ trống để người mua tranh tự viết chữ",
                ],
                "answer": "Tạo khoảng trống gợi sức tưởng tượng phong phú và chiều sâu ý cảnh",
                "transcript": "中国传统水墨画讲究“计白当黑”的留白艺术。画家往往不着一笔，却能在空白处营造出虚实相生、气韵生动的深邃意境，给观赏者留下了无限的遐想空间。(Zhōngguó chuántǒng shuǐmòhuà jiǎngjiù “jì bái dāng hēi” de liúbái yìshù. Huàjiā wǎngwǎng bù zhuó yì bǐ, què néng zài kòngbáichù yíngzào chū xūshí xiāngshēng, qìyùn shēngdòng de shēnsuì yìjìng, gěi guānshǎngzhě liúxià le wúxiàn de xiáxiǎng kōngjiān.)",
                "explanation": "留白 (chừa khoảng trống nghệ thuật), 意境深邃 (ý cảnh thâm sâu), 无限遐想 (không gian tưởng tượng vô hạn).",
                "audio_url": "https://translate.google.com/translate_tts?ie=UTF-8&tl=zh-CN&client=tw-ob&q=%E4%B8%AD%E5%9B%BD%E4%BC%A0%E7%BB%9F%E6%B0%B4%E5%A2%A8%E7%94%BB%E8%AE%B2%E7%A9%B6%E7%95%99%E7%99%BD%E8%89%BA%E6%9C%AF%EF%BC%8C%E5%9C%A8%E7%A9%BA%E7%99%BD%E5%A4%84%E8%90%A5%E9%80%A0%E5%87%BA%E6%B7%B1%E9%81%83%E6%84%8F%E5%A2%83%EF%BC%8C%E7%BB%99%E8%A7%82%E8%B5%8F%E8%80%85%E7%95%99%E4%B8%8B%E4%BA%86%E6%97%A0%E9%99%90%E7%9A%84%E9%81%90%E6%83%B3%E7%A9%BA%E9%97%B4%E3%80%82",
                "word_id": None,
            },
            {
                "id": "hsk6_l1_q2",
                "section": "listening",
                "prompt": "Người có trí tuệ thực sự được miêu tả như thế nào?",
                "options": [
                    "Khiêm nhường điềm tĩnh, không vội phô trương tài năng",
                    "Tìm mọi cách để tỏa sáng trước đám đông",
                    "Luôn khẳng định ý kiến cá nhân là đúng đắn",
                ],
                "answer": "Khiêm nhường điềm tĩnh, không vội phô trương tài năng",
                "transcript": "真正的智者往往大智若愚，他们不急于彰显自身的才华与锋芒，而是在静水流深中积蓄力量，以从容豁达的心态应对人生起伏。(Zhēnzhèng de zhìzhě wǎngwǎng dàzhìruòyú, tāmen bù jíyú zhāngxiǎn zìshēn de cáihuá yǔ fēngmáng, ér shì zài jìngshuǐ liúshēn zhōng jīxù lìliàng, yǐ cóngróng huòdá de xīntài yìngduì rénshēng qǐfú.)",
                "explanation": "大智若愚 (bậc đại trí thường giản dị, khiêm nhường), 不急于彰显才华 (không vội phô trương tài hoa), 从容豁达 (ung dung độ lượng).",
                "audio_url": "https://translate.google.com/translate_tts?ie=UTF-8&tl=zh-CN&client=tw-ob&q=%E7%9C%9F%E6%AD%A3%E7%9A%84%E6%99%BA%E8%80%85%E5%BE%80%E5%BE%80%E5%A4%A7%E6%99%BA%E8%8B%A5%E6%84%9A%EF%BC%8C%E4%BB%96%E4%BB%AC%E4%B8%8D%E6%80%A5%E4%BA%8E%E5%BD%B0%E6%98%BE%E8%87%AA%E8%BA%AB%E7%9A%84%E6%89%8D%E5%8D%8E%E4%B8%8E%E9%94%8B%E8%8A%92%E3%80%82",
                "word_id": None,
            },
            {
                "id": "hsk6_l1_q3",
                "section": "listening",
                "prompt": "Theo bài nói, thái độ đúng đắn trước nghịch cảnh là gì?",
                "options": [
                    "Xem khó khăn là cơ hội rèn luyện bản lĩnh và tích lũy kinh nghiệm",
                    "Tìm cách né tránh những thử thách mới",
                    "Chờ đợi sự giúp đỡ của người khác mà không hành động",
                ],
                "answer": "Xem khó khăn là cơ hội rèn luyện bản lĩnh và tích lũy kinh nghiệm",
                "transcript": "行至水穷处，坐看云起时。面对人生的逆境与坎坷，唯有将其视作磨砺意志、沉淀心境的良机，方能在重重迷雾中开辟出崭新的天地。(Xíng zhì shuǐ qióng chù, zuò kàn yún qǐ shí. Miànduì rénshēng de nìjìng yǔ kǎnkě, wéiyǒu jiāng qí shìzuò mólì yìzhì, chéndiàn xīnjìng de liángjī, fāng néng zài chóngchóng míwù zhōng kāipì chū zhǎnxīn de tiāndì.)",
                "explanation": "逆境与坎坷 (nghịch cảnh và gập ghềnh trắc trở), 磨砺意志 (rèn luyện ý chí), 沉淀心境 (lắng đọng tâm cảnh).",
                "audio_url": "https://translate.google.com/translate_tts?ie=UTF-8&tl=zh-CN&client=tw-ob&q=%E9%9D%A2%E5%AF%B9%E4%BA%BA%E7%94%9F%E7%9A%84%E9%80%86%E5%A2%83%E4%B8%8E%E5%9D%8E%E5%97%B7%EF%BC%8C%E5%94%AF%E6%9C%89%E5%B0%86%E5%85%B6%E8%A7%86%E4%BD%9C%E7%A3%A8%E7%A0%BA%E6%84%8F%E5%BF%97%E7%9A%84%E8%89%AF%E6%9C%BA%E3%80%82",
                "word_id": None,
            },
        ],
    },
]
