import 'package:flutter/material.dart';
import '../data/learning_data.dart';
import '../theme/app_theme.dart';
import '../widgets/common.dart';

class PracticeScreen extends StatefulWidget { const PracticeScreen({super.key}); @override State<PracticeScreen> createState()=>_PracticeScreenState(); }
class _PracticeScreenState extends State<PracticeScreen>{int current=0;String? selected;bool checked=false;int score=0;final options=const [['xin chào','cảm ơn','tạm biệt','xin lỗi'],['học tập','làm việc','nghỉ ngơi','đọc sách'],['bạn bè','gia đình','giáo viên','đồng nghiệp'],['yêu thích','ghét','muốn','có thể']];final answers=const ['xin chào','học tập','bạn bè','yêu thích'];@override Widget build(BuildContext context){final quizWords=[words[0],words[2],words[3],words[4]];final word=quizWords[current];return SafeArea(child:Column(children:[ScreenHeader(eyebrow:'Ôn tập thông minh',title:'Luyện tập',trailing:Text('${current+1}/4',style:const TextStyle(fontWeight:FontWeight.w800,color:AppTheme.red))),Padding(padding:const EdgeInsets.symmetric(horizontal:20),child:ProgressLine(value:(current+1)/4)),Expanded(child:SingleChildScrollView(padding:const EdgeInsets.all(20),child:Column(children:[const SizedBox(height:18),const Text('Hán tự này có nghĩa là gì?',style:TextStyle(color:Colors.grey,fontSize:13)),const SizedBox(height:24),HanziAvatar(word.hanzi,size:130,color:const Color(0xFFFFE9DE)),const SizedBox(height:10),Text(word.pinyin,style:const TextStyle(color:AppTheme.red,fontWeight:FontWeight.w700,fontSize:17)),const SizedBox(height:30),...options[current].map((option){final isSelected=selected==option;final isCorrect=checked&&option==answers[current];final isWrong=checked&&isSelected&&!isCorrect;return Padding(padding:const EdgeInsets.only(bottom:10),child:InkWell(onTap:checked?null:()=>setState(()=>selected=option),borderRadius:BorderRadius.circular(16),child:AnimatedContainer(duration:const Duration(milliseconds:180),width:double.infinity,padding:const EdgeInsets.all(17),decoration:BoxDecoration(color:isCorrect?const Color(0xFFE4F4E9):isWrong?const Color(0xFFFFE5E1):isSelected?const Color(0xFFFFEEE5):Colors.white,borderRadius:BorderRadius.circular(16),border:Border.all(color:isCorrect?AppTheme.jade:isWrong?AppTheme.red:isSelected?AppTheme.red:const Color(0xFFF0E8DE),width:isSelected?1.5:1)),child:Row(children:[Expanded(child:Text(option,style:const TextStyle(fontWeight:FontWeight.w700))),if(isCorrect)const Icon(Icons.check_circle,color:AppTheme.jade),if(isWrong)const Icon(Icons.cancel,color:AppTheme.red)]))));}),const SizedBox(height:14),SizedBox(width:double.infinity,child:FilledButton(onPressed:selected==null?null:()=>_next(),child:Text(checked?(current==3?'Xem kết quả':'Câu tiếp theo'):'Kiểm tra')))])))]));}
void _next(){if(!checked){setState((){checked=true;if(selected==answers[current])score++;});return;}if(current==3){showDialog(context:context,builder:(context)=>AlertDialog(icon:const Icon(Icons.emoji_events_rounded,color:AppTheme.orange,size:50),title:Text('Bạn đúng $score/4 câu!'),content:const Text('继续努力 · Tiếp tục cố gắng nhé!'),actions:[FilledButton(onPressed:(){Navigator.pop(context);setState((){current=0;selected=null;checked=false;score=0;});},child:const Text('Luyện lại'))]));}else{setState((){current++;selected=null;checked=false;});}}
}
